### ISSUE TITLE
使用之后会提示数据错误31-4302

### ISSUE THREAD

**Issue by Rakau** [Tsuk1ko/genshin-borderless-launcher#1]
好像是今天才出的

**Comment by Tsuk1ko** [comment]
使用的是最新版吗，我这里没有问题

另外可以确认下是否是删 blk 导致的

**Comment by Rakau** [comment]
> 使用的是最新版吗，我这里没有问题
> 
> 另外可以确认下是否是删 blk 导致的

不是的，我重新安装了能正常进去。然后用这个工具后就立马弹出来了

**Comment by Tsuk1ko** [comment]
所以使用的是本项目最新 releases 么？

是的话我也不清楚具体原因，网上搜一下倒是有很多解决方案可以参考

**Comment by Rakau** [comment]
> 所以使用的是本项目最新 releases 么？
> 
> 是的话我也不清楚具体原因，网上搜一下倒是有很多解决方案可以参考

是最新的releases的，现在停用了没问题了，不过一旦使用后出现错误代码，就算停用也无效了，必须重装了

**Comment by Tsuk1ko** [comment]
方便提供一下注册表`HKEY_CURRENT_USER\Software\miHoYo\原神`里面`Screenmanager`开头的那几个项的截图么

**Comment by Rakau** [comment]
> 方便提供一下注册表`HKEY_CURRENT_USER\Software\miHoYo\原神`里面`Screenmanager`开头的那几个项的截图么

使用工具
![屏幕截图 2020-10-30 133612](https://user-images.githubusercontent.com/33389179/97663688-34131280-1ab5-11eb-8dd7-6e9ccd9bf236.png)
![屏幕截图 2020-10-30 133644](https://user-images.githubusercontent.com/33389179/97663686-32494f00-1ab5-11eb-9c09-70d8564443d6.png)

没使用工具
![屏幕截图 2020-10-30 133423](https://user-images.githubusercontent.com/33389179/97663687-337a7c00-1ab5-11eb-88af-f0fd909e96b7.png)

**Comment by Tsuk1ko** [comment]
把 Fullscreen mode 改回`1`之后还会数据异常吗

**Comment by Rakau** [comment]
会，只要出现过错误代码只能重装，不用工具也会这样了

神代綺凜 <notifications@github.com> 于 2020年10月30日周五 17:39写道：

**Comment by Tsuk1ko** [comment]
那怪了，脚本唯一做过的事也就改了这一项注册表而已

**Comment by Rakau** [comment]
> 那怪了，脚本唯一做过的事也就改了这一项注册表而已

那我手动改下注册表看看，不通过程序

**Comment by Rakau** [comment]
> > 那怪了，脚本唯一做过的事也就改了这一项注册表而已
> 
> 那我手动改下注册表看看，不通过程序

不用，改了也只是假窗口全屏，我看下源码，对主程序注入了，可能是这个原因把

**Comment by Tsuk1ko** [comment]
不涉及内存注入，是用 windows 的 api 设置了窗口样式，去掉了 caption 和 sizebox（标题栏和窗口边框）

**Comment by Rakau** [comment]
已经解决，刚刚再研究了下，原神会对游戏目录检测，如果有非官方文件一律数据异常。破案了

**Comment by Tsuk1ko** [comment]
原来如此，你是放进游戏本体那个目录了是么，我是放在外面启动器那层所以没问题😂

**Comment by Rakau** [comment]
> 原来如此，你是放进游戏本体那个目录了是么，我是放在外面启动器那层所以没问题😂

是的，我为了方便放了一个genshin-wish-export然后也报错，我就想到肯定是检测文件了
